# Generated by Django 5.2 on 2025-04-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.DecimalField(decimal_places=1, max_digits=16, max_length=15)),
                ('restaurantAddress', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('gstin_number', models.DecimalField(blank=True, decimal_places=1, max_digits=15, max_length=20)),
                ('fssai_number', models.DecimalField(blank=True, decimal_places=1, max_digits=15, max_length=20)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('menu_pdf', models.FileField(blank=True, upload_to='menus/')),
                ('is_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='merchantRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='shakir', max_length=100)),
                ('number', models.DecimalField(decimal_places=1, default=54545, max_digits=15, max_length=50)),
                ('email', models.EmailField(default='shakir@GMAIL.COM', max_length=100)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('retypePassword', models.CharField(max_length=50)),
            ],
        ),
    ]
