# Generated by Django 5.2 on 2025-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='player_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
