# Generated by Django 5.2 on 2025-04-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantregistration',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='merchantregistration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='merchantregistration',
            name='number',
            field=models.DecimalField(decimal_places=1, max_digits=15, max_length=50),
        ),
    ]
