# Generated by Django 5.2 on 2025-04-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0002_alter_merchantregistration_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrestaurant',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='addrestaurant',
            name='menu_pdf',
        ),
    ]
