# Generated by Django 5.2 on 2025-08-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0002_restaurant_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='veg_or_nonveg',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], max_length=10, null=True, verbose_name='Veg / Non-Veg'),
        ),
    ]
