# Generated by Django 5.2 on 2025-05-03 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('driving_license', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('profile_photo', models.ImageField(upload_to='riders/profiles/')),
                ('aadhar_front', models.ImageField(upload_to='riders/aadhar/')),
                ('aadhar_back', models.ImageField(blank=True, null=True, upload_to='riders/aadhar/')),
                ('license_copy', models.ImageField(upload_to='riders/license/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=18, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_app.rider')),
            ],
        ),
        migrations.CreateModel(
            name='RiderEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orders_completed', models.PositiveIntegerField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_app.rider')),
            ],
        ),
    ]
