# Generated by Django 5.2 on 2025-06-15 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('driving_license', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('area', models.CharField(blank=True, help_text='Delivery area/zone', max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('profile_photo', models.ImageField(upload_to='riders/profiles/')),
                ('aadhar_front', models.ImageField(upload_to='riders/aadhar/')),
                ('license_copy', models.ImageField(upload_to='riders/license/')),
                ('aadhar_back', models.ImageField(blank=True, null=True, upload_to='riders/aadhar/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('total_assignments', models.PositiveIntegerField(default=0)),
                ('accepted_assignments', models.PositiveIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('today_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider',
                'verbose_name_plural': 'Riders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orders_completed', models.PositiveIntegerField()),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('distance_earning', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_earning', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_app.rider')),
            ],
            options={
                'verbose_name': 'Rider Earning',
                'verbose_name_plural': 'Rider Earnings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment to Rider'), ('pending', 'Pending Balance')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_app.rider')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('acceptance_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Weighted score based on response time', max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='user_app.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_app.rider')),
            ],
            options={
                'verbose_name': 'Order Assignment',
                'verbose_name_plural': 'Order Assignments',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('order',), name='unique_accepted_assignment_for_order')],
            },
        ),
        migrations.CreateModel(
            name='RiderBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=18)),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='rider_app.rider')),
            ],
            options={
                'verbose_name': 'Rider Bank Account',
                'verbose_name_plural': 'Rider Bank Accounts',
                'ordering': ['-is_primary', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('rider', 'is_primary'), name='unique_primary_bank_account_per_rider')],
            },
        ),
    ]
