# Generated by Django 5.2 on 2025-05-11 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rider_app', '0001_initial'),
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='user_app.order'),
        ),
        migrations.AddField(
            model_name='rider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderassignment',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_app.rider'),
        ),
        migrations.AddField(
            model_name='riderbankaccount',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='rider_app.rider'),
        ),
        migrations.AddField(
            model_name='riderearning',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_app.rider'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_app.rider'),
        ),
        migrations.AddConstraint(
            model_name='orderassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('order',), name='unique_accepted_assignment_for_order'),
        ),
        migrations.AddConstraint(
            model_name='riderbankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('rider', 'is_primary'), name='unique_primary_bank_account_per_rider'),
        ),
    ]
