# Generated by Django 5.2 on 2025-04-30 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='order',
            field=models.ForeignKey(default=1323, on_delete=django.db.models.deletion.CASCADE, to='user_app.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
