# Generated by Django 5.2 on 2025-05-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0001_initial'),
        ('user_app', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED')), fields=('order',), name='unique_accepted_assignment'),
        ),
        migrations.AddConstraint(
            model_name='orderassignment',
            constraint=models.UniqueConstraint(fields=('order', 'rider'), name='unique_rider_assignment'),
        ),
    ]
