# Generated by Django 5.2 on 2025-05-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0002_add_acceptance_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='acceptance_rate',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='last_rate_update',
        ),
    ]
