# Generated by Django 5.2 on 2025-05-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0002_orderassignment_unique_accepted_assignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Order Assignment', 'verbose_name_plural': 'Order Assignments'},
        ),
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rider', 'verbose_name_plural': 'Riders'},
        ),
        migrations.AlterModelOptions(
            name='riderearning',
            options={'ordering': ['-date'], 'verbose_name': 'Rider Earning', 'verbose_name_plural': 'Rider Earnings'},
        ),
    ]
