# Generated by Django 5.2 on 2025-05-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0003_alter_orderassignment_options_alter_rider_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='area',
            field=models.CharField(blank=True, help_text='Delivery area/zone', max_length=100),
        ),
    ]
