# Generated by Django 5.2 on 2025-05-07 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0003_remove_rider_acceptance_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
