# Generated by Django 5.2 on 2025-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0004_rider_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
