# Generated by Django 5.2 on 2025-05-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0005_alter_orderassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
