# Generated by Django 5.2 on 2025-05-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0006_alter_orderassignment_status'),
        ('user_app', '0007_remove_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderassignment',
            name='unique_accepted_assignment',
        ),
        migrations.AddConstraint(
            model_name='orderassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('order',), name='unique_accepted_assignment'),
        ),
    ]
