# Generated by Django 5.2 on 2025-05-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0008_remove_orderassignment_unique_accepted_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignment',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='riderearning',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riderearning',
            name='distance_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riderearning',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
