# Generated by Django 5.2 on 2025-05-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0009_orderassignment_distance_km_riderearning_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderearning',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
    ]
