# Generated by Django 5.2 on 2025-04-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='shakir', max_length=50, unique=True)),
                ('password', models.CharField(default='Shakir@2002', max_length=50, unique=True)),
            ],
        ),
    ]
