# Generated by Django 5.2 on 2025-05-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
