# Generated by Django 5.2 on 2025-06-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_order_special_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
