# Generated by Django 5.2 on 2025-06-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_ordermenuitem_alter_order_menu_items'),
    ]

    operations = [
    ]
