# Generated by Django 5.2 on 2025-05-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_pin_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dest_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Geocoded latitude of delivery address', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dest_lon',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Geocoded longitude of delivery address', max_digits=9, null=True),
        ),
    ]
