# Generated by Django 5.2 on 2025-06-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_customerfeedback_additional_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='item_ratings',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of menu_item_id: rating'),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='additional_comments',
            field=models.TextField(blank=True, help_text='Extra feedback', null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='comments',
            field=models.TextField(blank=True, help_text='General comments', null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='delivery_experience',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Experience with the delivery process', null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='item_quality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Quality of the food items', null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Main overall rating given by the customer.', null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='restaurant_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating for the restaurant overall', null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='rider_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating for the delivery rider', null=True),
        ),
    ]
