# Generated by Django 5.2 on 2025-05-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_order_delivery_address_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_longitude',
        ),
        migrations.AddField(
            model_name='order',
            name='dest_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geocoded latitude of delivery address', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dest_lon',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geocoded longitude of delivery address', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=512),
        ),
    ]
