# Generated by Django 5.2 on 2025-08-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_consent',
            field=models.BooleanField(default=False, help_text='I agree to receive order updates via WhatsApp'),
        ),
    ]
