# Generated by Django 5.2 on 2025-05-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dest_lat',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Geocoded latitude of delivery address', max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='dest_lon',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Geocoded longitude of delivery address', max_digits=9),
        ),
    ]
