# Generated by Django 5.2 on 2025-08-07 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_userprofile_whatsapp_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='retypePassword',
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='address',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit phone number')]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
