# Generated by Django 5.2 on 2025-08-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_userregistration_retypepassword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userRegistration',
        ),
    ]
