# Generated by Django 6.1.1 on 2026-10-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_delete_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_pin_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
