"""
Django settings for BITEQUE project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path):
    """Minimal .env loader so local development keeps working without
    exporting variables manually. Real environment variables always win."""
    try:
        with open(path) as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                key, _, value = line.partition('=')
                os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))
    except OSError:
        pass


_load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_DEV_FALLBACK_KEY = 'django-insecure-dev-only-key-change-me'
SECRET_KEY = os.environ.get('SECRET_KEY', _DEV_FALLBACK_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# Secure-by-default: DEBUG is only enabled when explicitly requested
# (local .env sets DEBUG=True; Render sets DEBUG=False).
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes')

# `collectstatic` runs during the Docker image build (no env vars, no
# .env) and `migrate` runs in the container entrypoint before gunicorn.
# Those preparation steps are allowed to boot without a key; anything
# that actually serves requests (gunicorn, runserver) still refuses to
# start without a real SECRET_KEY.
_NON_SERVING_COMMANDS = ('collectstatic', 'migrate')

if (
    not DEBUG
    and (not SECRET_KEY or SECRET_KEY == _DEV_FALLBACK_KEY)
    and not any(cmd in sys.argv for cmd in _NON_SERVING_COMMANDS)
):
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable must be set to a real secret when DEBUG is disabled."
    )

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# Absolute base URL for links that are built outside a request cycle
# (order e-mails, OneSignal push payloads). Priority order:
#   1. explicit SITE_URL env var
#   2. first configured trusted origin (production sets
#      CSRF_TRUSTED_ORIGINS=https://biteque.onrender.com)
#   3. the Django dev server
SITE_URL = (
    os.environ.get('SITE_URL')
    or (CSRF_TRUSTED_ORIGINS[0] if CSRF_TRUSTED_ORIGINS else 'http://localhost:8000')
).rstrip('/')

# Delivery PIN validity window (minutes) and wrong-guess budget.
DELIVERY_PIN_TTL_MINUTES = int(os.environ.get('DELIVERY_PIN_TTL_MINUTES', '30'))

# HTTPS / browser hardening (skipped in local dev and during `manage.py test`,
# where the test client issues plain HTTP requests).
_TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = (not DEBUG) and not _TESTING
SECURE_HSTS_SECONDS = 31536000 if (not DEBUG and not _TESTING) else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_app',
    'rider_app',
    'merchant_app',
    'django.contrib.humanize',
    "widget_tweaks",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False

ROOT_URLCONF = 'BITEQUE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'BITEQUE.context_processors.external_api_keys',
            ],
        },
    },
]

WSGI_APPLICATION = 'BITEQUE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, conn_health_checks=True),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', str(BASE_DIR / 'static')))

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

FILE_UPLOAD_PERMISSIONS = 0o644

DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB


#redirect_urls

#LOGIN_URL = 'rider-login'  
#LOGIN_REDIRECT_URL = '/rider/dashboard/'


#contact form backend / Brevo SMTP for verification emails

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'your-smtp-user')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'your-smtp-password')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'your-from-email@example.com')


BREVO_API_KEY = os.environ.get('BREVO_API_KEY', 'your-brevo-api-key')

MAILERSEND_API_KEY = os.environ.get('MAILERSEND_API_KEY', 'your-mailersend-api-key')
MAILERSEND_DOMAIN = os.environ.get('MAILERSEND_DOMAIN', 'your-mailersend-domain')


_LOG_DIR = BASE_DIR / 'logs'
_LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': str(_LOG_DIR / 'earnings_reset.log'),
        },
    },
    'loggers': {
        'rider_app': {
            'handlers': ['file'],
            'level': 'INFO',
        },
    },
}

OSRM_SERVER_URL = "http://router.project-osrm.org"

GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', 'your-google-maps-api-key')


RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', 'rzp_test_your_key_id')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', 'your-razorpay-key-secret')

#whatsapp oredr alerts

FAST2SMS_API_KEY = os.environ.get('FAST2SMS_API_KEY', 'your-fast2sms-api-key')  
FAST2SMS_URL = 'https://www.fast2sms.com/dev/bulkV2'
WHATSAPP_SENDER_ID = 'FSTSMS'  




